<?php

/**
 * @file
 * Provides the main code for the designs_view module.
 */

use Drupal\views_ui\ViewUI;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\cache\CachePluginBase;

/**
 * Implements hook_views_post_render().
 */
function designs_view_views_post_render(ViewExecutable $view, &$output, CachePluginBase $cache) {
  \Drupal::service('designs_view.handler')
    ->postRender($view, $output, $cache);
}

/**
 * Implements hook_views_ui_display_tab_alter().
 */
function designs_view_views_ui_display_tab_alter(&$build, ViewUI $view, $display_id) {
  \Drupal::service('designs_view.views_ui')
    ->displayTabAlter($build, $view, $display_id);
}

/**
 * Implements hook_config_schema_info_alter().
 */
function designs_view_config_schema_info_alter(&$definitions) {
  $definitions['views_display']['mapping']['design'] = [
    'type' => 'mapping',
    'label' => 'The design extensions for areas.',
    'mapping' => [
      'header' => [
        'type' => 'design_object',
      ],
      'footer' => [
        'type' => 'design_object',
      ],
      'empty' => [
        'type' => 'design_object',
      ],
      'pager' => [
        'type' => 'design_object',
      ],
    ],
  ];
}
