<?php

/**
 * @file
 * Allows users to quote posts or comments.
 */

/**
 * Update quote settings data.
 */
function quote_update_8201(): void {
  $config = \Drupal::configFactory()->getEditable('quote.settings');
  $allow_types = $config->get('quote_allow_types');
  $allow_types = !empty($allow_types) ? $allow_types : [];
  $config->set('quote_allow_types', array_filter($allow_types));
  $config->save();
}
