<?php

/**
 * @file
 * Module file for yasm.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function yasm_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.yasm':
      $text = file_get_contents(dirname(__FILE__) . '/README.md');

      if (\Drupal::moduleHandler()->moduleExists('markdown')) {
        // Use the Markdown filter to render the README.md file.
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $filter = \Drupal::service('plugin.manager.filter')->createInstance('markdown', ['settings' => $settings]);
        $output = $filter->process($text, 'en');
      }
      else {
        $output = '<pre>' . $text . '</pre>';
      }

      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function yasm_theme() {
  return [
    'yasm_wrapper' => [
      'variables' => [
        'content' => '',
        'attributes' => [],
      ],
    ],
    'yasm_columns' => [
      'variables' => [
        'items' => '',
        'attributes' => [],
        'content_attributes' => [],
      ],
    ],
    'yasm_card' => [
      'variables' => [
        'icon' => '',
        'label' => '',
        'count' => '',
      ],
    ],
    'yasm_item' => [
      'variables' => [
        'icon' => '',
        'label' => '',
        'count' => '',
      ],
    ],
    'yasm_tabs' => [
      'variables' => [
        'items' => [],
        'active_link' => '',
      ],
    ],
  ];
}
