<?php

/**
 * @file
 * Contains field_visibility_manager.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function field_visibility_manager_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.field_visibility_manager':
      $text = file_get_contents(dirname(__FILE__) . '/README.txt');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings       = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config         = ['settings' => $settings];
        $filter         = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;

}

/**
 * FieldRoleRestriction Form alter.
 */
function field_visibility_manager_form_alter(&$form, &$form_state, $form_id) {
  $value = \Drupal::config('field_visibility_manager.adminsettings')->get('permissions');
  $role = \Drupal::currentUser()->getRoles();
  foreach ($value as $field) {
    foreach ($role as $val) {
      $fieldname = $field['Field'];
      if ($field[$val] == '1') {
        $form[$fieldname]['#access'] = FALSE;
      }
    }
  }
}
