<?php

/**
 * @file
 * Group Node Access module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_help().
 */
function buttons_config_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    case 'help.page.buttons_config':
      $output = '';
      $output .= '<h2>' . t('About') . '</h2>';
      $output .= '<p>' . t('The Change Form Button Text module allows the user to change the text of the form submit button of any content type or media type form.') . '</p>';
      return $output;
  }
}

function buttons_config_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
  $configs = \Drupal::config('buttons_config.settings')->get('form_ids');

  $form_1 = '';
  $form_2 = '';
  foreach ($configs as $keys => $values) {
    $enabled = $values['enabled'];
    $ct_name = $values['form_id'];
    $form_isSave = $values['form_type'];
    foreach ($ct_name as $ct) {
      if (count($form_isSave) > 1) {
        $form_1 = $ct . "_form";
        $form_2 = $ct . "_edit_form";
      } else if ($form_isSave["0"]) {
        $form_1 = $ct . "_form";
      } else {
        $form_1 = $ct . "_edit_form";
      }
      if ($enabled == 1 && ($form_1 == $form_id || $form_2 == $form_id)) {
        $form['actions']['submit']['#value'] = $keys;
      }
    }
  }
}
