<?php

/**
 * @file
 * Hooks and functionality for the Group Commerce Order module.
 *
 * @I Implement group access control
 *    type     : bug
 *    priority : high
 *    labels   : security
 */

use Drupal\commerce_order\Entity\OrderTypeInterface;
use Drupal\commerceg\MachineName\Routing\Route;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * Clear the cached group content enabler plugin definitions when a new order
 * type is created so that it can be recognized without having to rebuild
 * caches.
 */
function commerceg_order_commerce_order_type_insert(
  OrderTypeInterface $order_type
) {
  \Drupal::service('plugin.manager.group_content_enabler')
    ->clearCachedDefinitions();
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 *
 * Clear the cached group content enabler plugin definitions when an existing
 * order type is deleted so that it can be removed from the available plugins
 * without having to rebuild caches.
 */
function commerceg_order_commerce_order_type_delete(
  OrderTypeInterface $order_type
) {
  \Drupal::service('plugin.manager.group_content_enabler')
    ->clearCachedDefinitions();
}

/**
 * Implements hook_entity_operation().
 *
 * @I Display the Orders operation only for groups with plugins installed
 *    type     : bug
 *    priority : low
 *    labels   : order
 */
function commerceg_order_entity_operation(EntityInterface $entity) {
  return \Drupal::service('commerceg.hook.entity_operation')->groupOperation(
    $entity,
    'access commerceg_order overview',
    Route::GROUP_ORDERS,
    t('Orders')
  );
}
