<?php

/**
 * @file
 * Provides the main code for the designs_entity module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function designs_entity_form_entity_view_display_edit_form_alter(&$form, FormStateInterface $form_state) {
  \Drupal::service('designs_entity.field_ui')
    ->displayFormAlter($form, $form_state);
}

/**
 * Validation for designs_entity_form_entity_view_display_edit_form_alter().
 */
function designs_entity_form_entity_view_display_form_validate(&$form, FormStateInterface $form_state) {
  \Drupal::service('designs_entity.field_ui')
    ->validateForm($form, $form_state);
}

/**
 * Submission for designs_entity_form_entity_view_display_edit_form_alter().
 */
function designs_entity_form_entity_view_display_form_submit(&$form, FormStateInterface $form_state) {
  \Drupal::service('designs_entity.field_ui')
    ->submitForm($form, $form_state);
}

/**
 * Callback for get row region.
 *
 * @param array $row
 *   The row.
 *
 * @return string
 *   The row region.
 */
function designs_entity_form_entity_view_display_row_region(array &$row) {
  return \Drupal::service('designs_entity.field_ui')
    ->getRowRegion($row);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function designs_entity_form_entity_form_display_edit_form_alter(&$form, FormStateInterface $form_state) {
  \Drupal::service('designs_entity.field_ui')
    ->displayFormAlter($form, $form_state);
}

/**
 * Implements hook_entity_view_alter().
 */
function designs_entity_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  \Drupal::service('designs_entity.display_handler')
    ->entityViewAlter($build, $entity, $display);
}

/**
 * Implements hook_entity_prepare_form().
 */
function designs_entity_entity_prepare_form(EntityInterface $entity, $operation, FormStateInterface $form_state) {
  \Drupal::service('designs_entity.display_handler')
    ->entityPrepareForm($entity, $operation, $form_state);
}

/**
 * Implements hook_form_alter().
 */
function designs_entity_form_alter(&$form, FormStateInterface $form_state) {
  \Drupal::service('designs_entity.display_handler')
    ->formAlter($form, $form_state);
}
