<?php

/**
 * @file
 * Module file for entity_logger module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\entity_logger\EntityTypeInfo;

/**
 * Implements hook_entity_type_alter().
 */
function entity_logger_entity_type_alter(array &$entity_types) {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(EntityTypeInfo::class)
    ->entityTypeAlter($entity_types);
}

/**
 * Implements hook_entity_operation().
 */
function entity_logger_entity_operation(EntityInterface $entity) {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(EntityTypeInfo::class)
    ->entityOperation($entity);
}

/**
 * Implements hook_entity_predelete().
 */
function entity_logger_entity_predelete(EntityInterface $entity) {
  /** @var \Drupal\entity_logger\EntityLogEntryStorageInterface $log_entry_storage */
  $log_entry_storage = \Drupal::entityTypeManager()->getStorage('entity_log_entry');
  $log_entry_storage->deleteForTargetEntity($entity);
}
