<?php

/**
 * @file
 * Contains config_terms_views.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function config_terms_views_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the config_terms module.
    case 'help.page.config_terms_views':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides views plugins for config terms.') . '</p>';
      return $output;

    default:
      return '';
  }
}
