<?php

use Drupal\Core\Config\Entity\ConfigEntityInterface;
use Drupal\Core\Entity\EntityDeleteForm;
use Drupal\Core\Entity\EntityFormInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\group\Entity\GroupContentTypeInterface;

function group_mandatory_form_alter(&$form, FormStateInterface $formState, $formId) {
  $formObject = $formState->getFormObject();
  if ($formObject instanceof EntityFormInterface && !$formObject instanceof EntityDeleteForm) {
    $config = $formObject->getEntity();
    if (
      $config instanceof GroupContentTypeInterface
      && ($contentPlugin = $config->getContentPlugin())
      // Is this even possible? Anyway, prevent it.
      && $contentPlugin->getGroupType()
    ) {
      $form['third_party_settings']['#tree'] = TRUE;
      $form['third_party_settings']['group_mandatory'] = [
        '#type' => 'fieldset',
        '#title' => t('Group mandatory'),
      ];
      $form['third_party_settings']['group_mandatory']['mandatory'] = [
        '#type' => 'checkbox',
        '#title' => t('Mandatory'),
        '#description' => t('This content must have a group.'),
        '#default_value' => $config->getThirdPartySetting('group_mandatory', 'mandatory', FALSE),
      ];
      $form['#entity_builders'][] = 'group_mandatory_entity_builder';
    }
  }
}

function group_mandatory_entity_builder(string $entityType, ConfigEntityInterface $configEntity, &$form, FormStateInterface $formState) {
  if ($formState->getValue(['third_party_settings', 'group_mandatory', 'mandatory'], FALSE)) {
    $configEntity->setThirdPartySetting('group_mandatory', 'mandatory', TRUE);
  }
  else {
    $configEntity->unsetThirdPartySetting('group_mandatory', 'mandatory');
  }
}

function group_mandatory_theme($existing, $type, $theme, $path) {
  return [
    'group_mandatory_list' => [
      'variables' => ['links' => NULL,],
    ],
  ];
}
