<?php

/**
 * @file
 * Primary module hooks for social_course_advanced_request module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_social_group_request_alter().
 */
function social_course_advanced_request_social_group_request_alter(array &$group_types): void {
  $group_types[] = 'course_advanced';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function social_course_advanced_request_form_social_group_request_membership_request_alter(array &$form): void {
  $form['#submit'][] = 'social_course_advanced_request_redirect';
}

/**
 * Submit callback for redirect on course about page after request to join.
 */
function social_course_advanced_request_redirect(array &$form, FormStateInterface $form_state): void {
  /** @var \Drupal\group\Entity\GroupInterface $group */
  $group = \Drupal::routeMatch()->getParameter('group');
  $form_state->setRedirect('view.group_information.page_group_about', ['group' => $group->id()]);
}
