<?php

/**
 * @file
 * Maestro Task Console module file. Provides Drupal Hook implementations.
 */

/**
 * Implements hook_theme().
 */
function maestro_taskconsole_theme($existing, $type, $theme, $path) {
  return [
    'taskconsole_status_bar' => [
      'variables' => [
        'stage_count' => 0,
        'stage_messages' => [],
        'current_stage' => 0,
        'current_stage_message' => '',
      ],
    ],

    'taskconsole_views' => [
      'variables' => [
    // The html string of task information.
        'task_information' => '',
        'title' => '',
      ],
    ],

  ];
}
