<?php

/**
 * @file
 * Freelinking prepopulate module file.
 *
 * Provides a node/add links via the Create Node plugin intended for use
 * primarily as a "failover" when other node plugins fail.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function freelinking_prepopulate_help($route_name, RouteMatchInterface $route) {
  $hint = '';
  // @todo Re-implement advanced_help_hint.
  if ($route_name === 'help.page.freelinking_prepopulate') {
    if (\Drupal::hasService('advanced_help_hint.gethint')) {
      /** @var \Drupal\advanced_help_hint\Hint $hintService */
      $hintService = \Drupal::service('advanced_help_hint.gethint');
      $hint = '<p>' . $hintService->produceHint('freelinking', 'https://www.drupal.org/docs/8/modules/freelinking', TRUE) . '</p>';
    }
    return '<p>' . t('This module provides plugins for Freelinking to prepopulate node create.') . '</p>' . $hint;
  }
}
