<?php

use Drupal\expose_actions\Plugin\Menu\LocalAction\ExposeAction;

/**
 * Implements hook_menu_local_actions_alter().
 *
 * @param $local_actions
 *
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 */
function expose_actions_menu_local_actions_alter(&$local_actions) {
  /** @var \Drupal\system\Entity\Action $action */
  foreach (Drupal::entityTypeManager()->getStorage('action')->loadMultiple() as $id => $action) {
    if ($action->status()) {
      $def = $action->getPluginDefinition();
      $route_name = empty($def['confirm_form_route_name']) ?
        'expose_actions.confirm' :
        $def['confirm_form_route_name'];
      $local_actions['action_' . $id] = [
        'id' => 'action_' . $id,
        'title' => $action->label(),
        'weight' => NULL,
        'route_name' => $route_name,
        'route_parameters' => [
          'action' => $id,
        ],
        'options' => [],
        'appears_on' => [
          'entity.' . $action->getType() . '.canonical',
        ],
        'class' => ExposeAction::class,
        'provider' => 'expose_actions',
      ];
    }
  }
}

/**
 * Implements hook_perm().
 */
function expose_actions_perm() {

}
