<?php

/**
 * @file
 * Provides the main code for the designs_field module.
 */

use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FormatterInterface;
use Drupal\Core\Field\WidgetInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_field_widget_third_party_settings_form().
 */
function designs_field_field_widget_third_party_settings_form(WidgetInterface $plugin, FieldDefinitionInterface $field_definition, $form_mode, $form, FormStateInterface $form_state) {
  return \Drupal::service('designs_field.wrapper')
    ->buildConfigurationForm($plugin, $field_definition, $form, $form_state);
}

/**
 * Implements hook_field_widget_settings_summary_alter().
 */
function designs_field_field_widget_settings_summary_alter(&$summary, $context) {
  return \Drupal::service('designs_field.wrapper')
    ->buildSummary($context['widget'], $summary);
}

/**
 * Implements hook_field_formatter_third_party_settings_form().
 */
function designs_field_field_formatter_third_party_settings_form(FormatterInterface $plugin, FieldDefinitionInterface $field_definition, $view_mode, $form, FormStateInterface $form_state) {
  return \Drupal::service('designs_field.wrapper')
    ->buildConfigurationForm($plugin, $field_definition, $form, $form_state);
}

/**
 * Implements hook_field_formatter_settings_summary_alter().
 */
function designs_field_field_formatter_settings_summary_alter(&$summary, $context) {
  return \Drupal::service('designs_field.wrapper')
    ->buildSummary($context['formatter'], $summary);
}

/**
 * Implements hook_entity_display_build_alter().
 */
function designs_field_entity_display_build_alter(&$build, $context) {
  \Drupal::service('designs_field.wrapper')->entityDisplayBuildAlter($build, $context);
}

/**
 * Implements hook_entity_view_alter().
 */
function designs_field_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  \Drupal::service('designs_field.wrapper')->entityViewAlter($build, $entity);
}

/**
 * Implements hook_form_alter().
 */
function designs_field_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('designs_field.wrapper')->entityFormAlter($form, $form_state);
}
