anu_lms_assessments.assessment_question_result_type.*:
  type: config_entity
  label: 'Question result type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
