<?php

/**
 * @file
 * The entity_version_test module.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_entity_base_field_info().
 */
function entity_version_test_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  if ($entity_type->id() !== 'entity_test_rev') {
    return $fields;
  }

  $fields['version'] = BaseFieldDefinition::create('entity_version')
    ->setLabel(t('Entity version'))
    ->setDescription(t('Entity version'))
    ->setTranslatable(FALSE)
    ->setRevisionable(TRUE);

  return $fields;
}
