<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_render().
 */
function tasks_olivero_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->id() == 'tasks' || $view->id() == 'tasks_manage') && ($view->getDisplay()->display['id'] == 'block_1')) {
    $view->element['#attached']['library'][] = 'tasks_olivero/olivero_display';
    $view->element['#attached']['library'][] = 'tasks_olivero/olivero_tweaks';
  }
}
