<?php

/**
 * @file
 * Allows site administrators to export single configuration with one click.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function config_single_export_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'config_single_export_form') {
    $form['actions']['submit'] = [
      '#type' => 'submit',
      '#value' => 'Export',
    ];
    $form['actions']['submit']['#submit'][] = 'config_single_export_form_submit';
  }
}

/**
 * Implements hook_form_submit().
 */
function config_single_export_form_submit($form, FormStateInterface $form_state) {
  $config_type = $form_state->getValue('config_type');
  $config_name = $form_state->getValue('config_name');
  $export = $form_state->getValue('export');
  if ($config_type && $config_name) {
    if ($form_state->getValue('config_type') !== 'system.simple') {
      $entity_manager = \Drupal::service('entity_type.manager');
      $definition = $entity_manager->getDefinition($config_type);
      $name = $definition->getConfigPrefix() . '.' . $config_name;
    }
    // The config name is used directly for simple configuration.
    else {
      $name = $config_name;
    }
    $filename = $name . '.yml';
    file_put_contents(\Drupal::service('file_system')->getTempDirectory() . DIRECTORY_SEPARATOR . $filename, $export);
    $form_state->setRedirect('config.single_export_download', ['filename' => $filename]);
  }
}

/**
 * Implements hook_file_download().
 */
function config_single_export_file_download($uri) {
  $scheme = \Drupal::service('stream_wrapper_manager')->getScheme($uri);
  if ($scheme == 'temporary') {
    $target = \Drupal::service('stream_wrapper_manager')->getTarget($uri);
    $disposition = 'attachment; filename="' . $target . '"';
    return [
      'Content-disposition' => $disposition,
    ];
  }
}
