<?php

/**
 * @file
 * Contact default fields override module file.
 */

use Drupal\contact_default_fields_override\Form\MessageForm;
use Drupal\contact\Entity\ContactForm;
use Drupal\Core\Field\Entity\BaseFieldOverride;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\contact_default_fields_override\Element;

/**
 * {@inheritdoc}
 */
function contact_default_fields_override_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle, array $base_field_definitions) {
  if ($entity_type->id() !== 'contact_message' || $bundle === NULL) {
    return [];
  }

  $contactForm = ContactForm::load($bundle);

  if ($contactForm === NULL) {
    return;
  }

  $fields = [];

  $settings = $contactForm->getThirdPartySettings('contact_default_fields_override');

  foreach (contact_default_fields_override_get_fields_to_override() as $field_to_override) {
    $field = BaseFieldOverride::createFromBaseFieldDefinition($base_field_definitions[$field_to_override], $bundle);

    if (isset($settings[$field_to_override . '_required'])) {
      $field->setRequired($settings[$field_to_override . '_required']);
    }

    $fields[$field_to_override] = $field;
  }

  return $fields;
}

/**
 * Determines which fields are overridable.
 *
 * See \Drupal\contact\Entity\Message::baseFieldDefinitions for all available
 * options.
 *
 * @return string[]
 *   The fields to override.
 */
function contact_default_fields_override_get_fields_to_override() {
  $overidable_fields = [
    'name',
    'mail',
    'subject',
    'message',
  ];

  Drupal::moduleHandler()
    ->invokeAll('contact_default_fields_override_alter', [&$overidable_fields]);

  return $overidable_fields;
}

/**
 * {@inheritDoc}
 */
function contact_default_fields_override_entity_type_alter(array &$entity_types) {
  if (!isset($entity_types['contact_message'])) {
    return;
  }

  $entity_types['contact_message']->setHandlerClass('form', ['default' => MessageForm::class]);
}

/**
 * {@inheritDoc}
 */
function contact_default_fields_override_element_info_alter(&$info) {
  $elements = [
    'textfield',
    'textarea',
    'item',
    'email',
  ];
  foreach ($elements as $element) {
    if (isset($info[$element])) {
      $info[$element]['#pre_render'][] = [Element::class, 'preRender'];
    }
  }
}
